/**
 * TaxWise Nigeria — JSX Compiler
 * 
 * Reads index.html (JSX source), compiles JSX to plain JS using Sucrase,
 * writes compiled output to dist/index.html.
 * 
 * Run: node compile.js
 * Called automatically by GitHub Actions on every push to main.
 */

const fs = require('fs');
const path = require('path');
const { transform } = require('sucrase');

const SRC = path.join(__dirname, 'index.html');
const DIST_DIR = path.join(__dirname, 'dist');
const DIST = path.join(DIST_DIR, 'index.html');

// Read source
const html = fs.readFileSync(SRC, 'utf8');

// Find the JSX script block
const JSX_OPEN = '<script type="text/babel">';
const JSX_CLOSE = '</script>';

const jsxStart = html.indexOf(JSX_OPEN);
if (jsxStart === -1) {
  // No text/babel — already compiled or plain JS, just copy
  fs.mkdirSync(DIST_DIR, { recursive: true });
  fs.copyFileSync(SRC, DIST);
  
  // Copy other files (landing, privacy, terms)
  ['landing.html','privacy.html','terms.html','manifest.json'].forEach(f => {
    const src = path.join(__dirname, f);
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(DIST_DIR, f));
  });
  
  console.log('No JSX found — copied as-is to dist/');
  process.exit(0);
}

const codeStart = jsxStart + JSX_OPEN.length;
const jsxEnd = html.indexOf(JSX_CLOSE, codeStart);
const jsxSource = html.slice(codeStart, jsxEnd);

console.log(`Source JSX: ${(jsxSource.length / 1024).toFixed(1)}KB`);

// Compile JSX → plain JS
let compiled;
try {
  compiled = transform(jsxSource, { transforms: ['jsx'] }).code;
  console.log(`Compiled JS: ${(compiled.length / 1024).toFixed(1)}KB`);
} catch (e) {
  console.error('JSX compile error:', e.message);
  process.exit(1);
}

// Add React globals at top of compiled output
// (Sucrase transforms JSX to React.createElement but doesn't inject React)
const reactGlobals = [
  '/* TaxWise Nigeria — compiled by Sucrase, do not edit this file directly */',
  '/* Edit index.html (JSX source) and push — GitHub Actions recompiles automatically */',
  '',
  '// Ensure React globals are available from UMD builds',
  'var React = window.React;',
  'var ReactDOM = window.ReactDOM;',
  '',
].join('\n');

const finalJS = reactGlobals + compiled;

// Build output HTML:
// - Replace <script type="text/babel">...</script> with <script>compiledJS</script>
// - Remove Babel CDN (not needed)
// - Keep everything else identical
let output = html;

// Remove Babel CDN script tag
output = output.replace(
  '<script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>',
  '<!-- Babel removed: JSX pre-compiled by Sucrase at build time -->'
);

// Replace JSX block with compiled JS
const beforeJSX = output.slice(0, jsxStart);
const afterJSX = output.slice(jsxEnd + JSX_CLOSE.length);
output = beforeJSX + '<script>\n' + finalJS + '\n</script>' + afterJSX;

// Write to dist/
fs.mkdirSync(DIST_DIR, { recursive: true });
fs.writeFileSync(DIST, output, 'utf8');

// Copy other static files
['landing.html', 'privacy.html', 'terms.html', 'manifest.json'].forEach(f => {
  const src = path.join(__dirname, f);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(DIST_DIR, f));
    console.log(`Copied: ${f}`);
  }
});

console.log(`\nBuild complete: dist/index.html (${(output.length / 1024).toFixed(1)}KB)`);
console.log('Deploy: GitHub Pages will serve from dist/');
